# Generated by Django 3.2.9 on 2021-11-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingQueryData',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('rdc_web_url', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('line', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('prop_status', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('baths_full', models.IntegerField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('agents', models.CharField(blank=True, max_length=1000, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.CharField(blank=True, max_length=100, null=True)),
                ('client_display_flags', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('lot_size_units', models.CharField(blank=True, max_length=100, null=True)),
                ('mls', models.CharField(blank=True, max_length=100, null=True)),
                ('data_source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('presentation_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_change', models.IntegerField(blank=True, null=True)),
                ('is_new_listing', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdata.housingquerydata')),
            ],
        ),
    ]
