# Generated by Django 3.2.9 on 2021-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_housedatapoint_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedatapoint',
            name='client_display_flags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
