# Generated by Django 3.2.9 on 2021-11-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_alter_housedatapoint_client_display_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedatapoint',
            name='mls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
